### ISSUE TITLE
Dir not deleted on  graceful change with Node.js ≥ 12

### ISSUE THREAD

**Issue by guimard** [raszi/node-tmp#209]
## Operating System
- [x] Linux
- [ ] Windows 7
- [ ] Windows 10
- [ ] MacOS
- other: 

## NodeJS Version
- [ ] 0.x
- [ ] 4.x
- [ ] 6.x
- [ ] 7.x
- [x] other: 12

## Tmp Version
TBD: 0.1.0

## Expected Behavior
TBD: remove tmp directory on graceful cleanup

## Experienced Behavior
TBD: did not, proven by tests :

```
  341 passing (3s)
  2 failing

  1) tmp
       #dirSync()
         when running standard outband tests
           on graceful cleanup:

      AssertionError [ERR_ASSERTION]: /tmp/tmp-895811RisWt1aul3Ir should not exist
      + expected - actual

      -false
      +true
      
      at Object.assertDoesNotExist (test/assertions.js:67:10)
      at test/dir-sync-test.js:56:24
      at _close (test/child-process.js:58:7)
      at Socket._stderrEnd (test/child-process.js:80:5)
      at Pipe.<anonymous> (net.js:659:12)

  2) tmp
       #dir()
         when running standard outband tests
           on graceful cleanup:

      AssertionError [ERR_ASSERTION]: /tmp/tmp-895860AHeHf1UUAj7m should not exist
      + expected - actual

      -false
      +true
      
      at Object.assertDoesNotExist (test/assertions.js:67:10)
      at test/dir-test.js:65:24
      at _close (test/child-process.js:58:7)
      at Socket._stderrEnd (test/child-process.js:80:5)
      at Pipe.<anonymous> (net.js:659:12)
```

**Comment by silkentrance** [comment]
Fixed with #198.
