### ISSUE TITLE
Test suite failure

### ISSUE THREAD

**Issue by joliss** [raszi/node-tmp#68]
I'd like to send a minor fix for something, but the test suite isn't passing for me on master. I'm using Node v4.1.2 on Ubuntu 14.04.

```
$ npm test

> tmp@0.0.28 test /home/ubuntu/src/node-tmp
> vows test/*-test.js

·············✗✗✗·································· ·····························✗✗✗✗······················· ········································ ················································ ···············


    when using name
      ✗ should return with a name
      Error: Could not get a unique tmp filename, max tries reached
      at _getTmpNameSync (/home/ubuntu/src/node-tmp/lib/tmp.js:198:9)
      at Object._createTmpDirSync [as dirSync] (/home/ubuntu/src/node-tmp/lib/tmp.js:328:14)
      at Object.vows.describe.addBatch.when using name.topic (/home/ubuntu/src/node-tmp/test/dir-sync-test.js:68:18)
      at run (/home/ubuntu/src/node-tmp/node_modules/vows/lib/vows/suite.js:134:35)
      at EventEmitter.<anonymous> (/home/ubuntu/src/node-tmp/node_modules/vows/lib/vows/suite.js:234:40)
      at emitOne (events.js:82:20)
      at EventEmitter.emit (events.js:169:7)
      at EventEmitter.options.Emitter.emit (/home/ubuntu/src/node-tmp/node_modules/vows/lib/vows.js:237:24)
      at /home/ubuntu/src/node-tmp/node_modules/vows/lib/vows/suite.js:169:45
      at doNTCallback0 (node.js:408:9)

      ✗ should have the provided name
      Error: Could not get a unique tmp filename, max tries reached
      at _getTmpNameSync (/home/ubuntu/src/node-tmp/lib/tmp.js:198:9)
      at Object._createTmpDirSync [as dirSync] (/home/ubuntu/src/node-tmp/lib/tmp.js:328:14)
      at Object.vows.describe.addBatch.when using name.topic (/home/ubuntu/src/node-tmp/test/dir-sync-test.js:68:18)
      at run (/home/ubuntu/src/node-tmp/node_modules/vows/lib/vows/suite.js:134:35)
      at EventEmitter.<anonymous> (/home/ubuntu/src/node-tmp/node_modules/vows/lib/vows/suite.js:234:40)
      at emitOne (events.js:82:20)
      at EventEmitter.emit (events.js:169:7)
      at EventEmitter.options.Emitter.emit (/home/ubuntu/src/node-tmp/node_modules/vows/lib/vows.js:237:24)
      at /home/ubuntu/src/node-tmp/node_modules/vows/lib/vows/suite.js:169:45
      at doNTCallback0 (node.js:408:9)

      ✗ should be a directory
        » should exist // dir-sync-test.js:15

      ✗ should not return with an error
        » expected null, got { stack: 'Error: Could not get a unique tmp filename, max tries reached /tmp/using-name\n    at _pathExists (/home/ubuntu/src/node-tmp/lib/tmp.js:164:19)\n    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)', message: 'Could not get a unique tmp filename, max tries reached /tmp/using-name' } // vows.js:132

      ✗ should return with a name
        » expected undefined to be a String // base.js:90

      ✗ should be a directory
        » should exist // dir-test.js:15

      ✗ should have the provided name
        » should have the provided name // base.js:104
  ✗ Errored » 202 honored ∙ 5 broken ∙ 2 errored (0.625s)
  npm ERR! Test failed.  See above for more details.
$ npm ls
tmp@0.0.28 /home/ubuntu/src/node-tmp
├── os-tmpdir@1.0.1
└─┬ vows@0.7.0
  ├── diff@1.0.8
  └── eyes@0.1.8
```

Is there anything I can do to debug this further?

**Comment by raszi** [comment]
It seems like that you have too many temp files in your TMP directory and node-tmp cannot generate a new one for you after a couple of tries.

Could you try it again after removing the temp files?

```sh
rm -vrf ${TMPDIR}/{foo,tmp,something,complicated,clike,using}*
```

**Comment by joliss** [comment]
Hm, it actually works now - I can't reproduce it anymore. Very strange. If it pops up again I'll dig more.

Thanks!

**Comment by raszi** [comment]
There was an issue with the old versions, so probably those old versions filled up your TMP directory when you were running the tests.

**Comment by joliss** [comment]
It's happening again... The reason indeed seems to be left-overs from a previous test run, in particular at `/tmp/using-name` - because the name is fixed, node-tmp has no chance to generate a unique name.

The tests causing the failure are in [dir-sync-test.js](https://github.com/raszi/node-tmp/blob/c196bcb0b010da13675fd9572c67423f64057f69/test/dir-sync-test.js#L66-L78) and [dir-test.js](https://github.com/raszi/node-tmp/blob/c196bcb0b010da13675fd9572c67423f64057f69/test/dir-test.js#L68-L77). Similar presumably for file-sync-test.js and file-test.js.

I tried fixing it by nesting the "name" test inside another tmp dir (`tmp.dirSync({ name: 'using-name', dir: tmp.dirSync().name })`), but then the assertions break, and vows makes it hard to fix this.

I'm mentioning this just in case you have an idea how to fix it. But maybe it's not worth the effort :)
